swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  # PHASE 2
  /user/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: User Transactions
      description: Returns a list of user transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Bearer token
          required: true
        - in: path
          name: accountId
          # il faut l'id du compte pour trouver les transactions
          description: transactions retrieve with user id
          type: string
          required: true
      responses:
        '200':
          description: transactions successfully
          schema:
            $ref: '#/definitions/userTransactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: User Transaction Details
      description: Return a transaction details
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Bearer token
          required: true
        - in: path
          name: transactionId
          description: transactions details retrieve with transaction id
          required: true
          type: string
        - in: path
          name: accountId
          # il faut l'id du compte pour trouver les transactions
          description: transactions details retrieve with user id
          type: string
          required: true
      responses:
        '200':
          description: transaction details successfully
          schema:
            $ref: '#/definitions/userTransactionsDetails'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    # methode put pour changer categorie ou note
    put:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: User Transaction category & notes
      description: update transaction category or notes
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Bearer token
          required: true
        - in: path
          name: transactionId
          description: Transaction Id to be updated
          required: true
          type: string
        - in: path
          name: accountId
          # il faut l'id du compte pour trouver les transactions
          description: account Id to be updated
          type: string
          required: true
        - in: body
          name: body
          description: Update user transaction category / notes
          required: true
          schema:
            $ref: '#/definitions/userTransactionUpdate'
      responses:
        '200':
          description: User transaction updated successully
          schema:
            $ref: '#/definitions/userTransactionsDetails'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    # methode post pour ajouter une note
    post:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: User Transaction Add Notes
      description: User Transaction Add Notes
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Bearer token
          required: true
        - in: path
          name: transactionId
          description: Transaction Id to be updated
          required: true
          type: string
        - in: path
          name: accountId
          # il faut l'id du compte pour trouver les transactions
          description: account Id to be updated
          type: string
          required: true
        - in: body
          name: body
          description: Update user transaction notes
          required: true
          schema:
            $ref: '#/definitions/userTransactionsDetailsNotes'
      responses:
        '200':
          description: User transaction notes updated successully
          schema:
            $ref: '#/definitions/userTransactionsDetails'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: User Transaction Notes deleting
      description: deleting transaction notes
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Bearer token
          required: true
        - in: path
          name: transactionId
          description: Transaction Id to be updated
          required: true
          type: string
        - in: path
          name: accountId
          # il faut l'id du compte pour trouver les transactions
          description: account Id to be updated
          type: string
          required: true
      responses:
        '200':
          description: User transaction notes deleted successully
          schema:
            $ref: '#/definitions/TransactionDetailsDelete'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  # PHASE 2
  userTransactions:
    type: object
    properties:
      body:
        type: array
        items:
          type: object
        properties:
          transactionId:
              type: string
          amount:
            type: number
          date:
            type: string
          description:
            type: string
          balance:
            type: number
  userTransactionsDetails:
    type: object
    properties:
      transactionId:
        type: string
      amount:
        type: number
      date:
        type: string
      description:
        type: string
      balance:
        type: number
      transactiontype:
        type: string
      category:
        type: string
      notes:
        type: string
  userTransactionUpdate:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
  userTransactionsDetailsNotes:
    type: object
    properties:
      notes:
        type: string
  TransactionDetailsDelete:
    type: object
    properties:
      status:
        type: integer
        description: request response status
      body:
        type: object
        properties:
          transactionId:
            type: string
          amount:
            type: number
            description: transaction amount
          date:
            type: string
            description: transaction date
          description:
            type: string
            description: transaction description
          balance:
            type: number
            description: account balance
          transactiontype:
            type: string
            description: account balance
          category:
            type: string
            description: transaction category
          notes:
            type: string
            description: transaction notes